### ISSUE TITLE
 ppt uploaded to the wrong directory 

### ISSUE THREAD

**Issue by XP2016India** [XP2016India/All-Power-Point-Slides#1]
Riya you have added  the ppt to the wrong directory , upload it to the correct one 

check this two 
Power Of Measurement Agility Meetu arora.pptx  
devops_like_la.pptx.pptx

**Comment by riya-SIQ** [comment]
All files going to a new folder Ranjith!

**Comment by XP2016India** [comment]
the issue is because the directory "Speaker presentations for XP Conference" has spaces , i an seeing how to rename , i might need to work on the console interface to rename it , it will take 15 min

**Comment by rtharayil** [comment]
ok plz upload now

**Comment by rtharayil** [comment]
after successful upload close this issue
